import pyfiglet
import os
os.system('clear')
#os.system('cls')
print(pyfiglet.figlet_format('Statistics   ', font='dotmatrix'))
print('')
print('')
print('What do you want to compute: \n1. Mean\n2. Median\n3. Mode')
choice = input('Enter Here[1/2/3] : ')
if choice == '1':
	frequentno = input('How many Intervals do you have:\n5\n6\n7\nEnter: ')
	if frequentno == '5':
		print('Please Compute the Xi of the ci them write it as if we as for lower limit- upper limit you and our system will get confused \nhint: Xi of ci = (lower limit + upper limit)/ 2')
		firstxi = int(input('Xi of ci 1: '))
		twoxi = int(input('Xi of ci 2: '))
		threexi = int(input('Xi of ci 3: '))
		fourxi = int(input('Xi of ci 4: '))
		fifxi = int(input('Xi of ci 5: '))
		f1 = int(input('frequency of ci 1: '))
		f2 = int(input('frequency of ci 2: '))
		f3 = int(input('frequency of ci 3: '))
		f4 = int(input('frequency of ci 4: '))
		f5 = int(input('frequency of ci 5: '))
		print('---------------------------------------------------')
		print('|         xi              |        Frequency      |')
		print('---------------------------------------------------')
		print('|       ',firstxi,'               |        ',f1,'        |')
		print('|       ',twoxi,'               |        ',f2,'        |')
		print('|       ',threexi,'               |        ',f3,'        |')
		print('|       ',fourxi,'               |        ',f4,'        |')
		print('|       ',fifxi,'               |        ',f5,'        |')
		print('---------------------------------------------------')
		sigmaxifi = (firstxi * f1) + (twoxi * f2) + (threexi * f3) + (fourxi * f4) + (fifxi * f5)
		sigmafi = f1 + f2 + f3 + f4 + f5
		xdash = sigmaxifi/sigmafi
		print('the Mean is : ',xdash)
	elif frequentno == '6':
		print('Please Compute the Xi of the ci them write it \nhint: Xi of ci = (lower limit + upper limit)/ 2')
		firstxi2 = int(input('Xi of ci 1: '))
		twoxi2 = int(input('Xi of ci 2: '))
		threexi2 = int(input('Xi of ci 3: '))
		fourxi2 = int(input('Xi of ci 4: '))
		fifxi2 = int(input('Xi of ci 5: '))
		sixfi = int(input('Xi of ci 6: '))
		f12 = int(input('frequency of ci 1: '))
		f22 = int(input('frequency of ci 2: '))
		f32 = int(input('frequency of ci 3: '))
		f42 = int(input('frequency of ci 4: '))
		f52 = int(input('frequency of ci 5: '))
		f6 = int(input('frequency of ci 6: '))
		print('---------------------------------------------------')
		print('|         xi              |        Frequency      |')
		print('---------------------------------------------------')
		print('|       ',firstxi2,'               |        ',f12,'        |')
		print('|       ',twoxi2,'               |        ',f22,'        |')
		print('|       ',threexi2,'               |        ',f32,'        |')
		print('|       ',fourxi2,'               |        ',f42,'        |')
		print('|       ',fifxi2,'               |        ',f52,'        |')
		print('|       ',sixxi,'               |        ',f6,'        |')
		print('---------------------------------------------------')
		sigmaxifi1 = (firstxi2 * f12) + (twoxi2 * f22) + (threexi2 * f32) + (fourxi2 * f42) + (fifxi2 * f52) + (sixfi * f6)
		sigmafi1 = f12 + f22 + f32 + f42 + f52 + f6
		xdash1 = sigmaxifi1/sigmafi1
		print('the Mean is : ',xdash1)
	elif frequentno == '7':
		print('Please Compute the Xi of the ci them write it \nhint: Xi of ci = (lower limit + upper limit)/ 2')
		firstxi1 = int(input('Xi of ci 1: '))
		twoxi1 = int(input('Xi of ci 2: '))
		threexi1 = int(input('Xi of ci 3: '))
		fourxi1 = int(input('Xi of ci 4: '))
		fifxi1 = int(input('Xi of ci 5: '))
		sixxi1 = int(input('Xi of ci 6: '))
		sevxi = int(input('Xi of ci 7: '))
		f11 = int(input('frequency of ci 1: '))
		f21 = int(input('frequency of ci 2: '))
		f31 = int(input('frequency of ci 3: '))
		f41 = int(input('frequency of ci 4: '))
		f51 = int(input('frequency of ci 5: '))
		f61 = int(input('frequency of ci 6: '))
		f7 = int(input('frequency of ci 7: '))
		print('---------------------------------------------------')
		print('|         xi              |        Frequency      |')
		print('---------------------------------------------------')
		print('|       ',firstxi1,'               |        ',f11,'        |')
		print('|       ',twoxi1,'               |        ',f21,'        |')
		print('|       ',threexi1,'               |        ',f31,'        |')
		print('|       ',fourxi1,'               |        ',f41,'        |')
		print('|       ',fifxi1,'               |        ',f51,'        |')
		print('|       ',sixxi1,'               |        ',f61,'        |')
		print('|       ',sevxi,'               |        ',f7,'        |')
		print('---------------------------------------------------')
		sigmaxifi3 = (firstxi1 * f11) + (twoxi1 * f21) + (threexi1 * f31) + (fourxi1 * f41) + (fifxi1 * f51) + (sixxi1 * f61) + (sevxi * f7)
		sigmafi3 = f11 + f21 + f31 + f41 + f51 + f61 + f7
		xdash5 = sigmaxifi3/sigmafi3
		print('the Mean is : ',xdash5)
	else:
		print('INVALID INPUT. Please Try Again')
elif choice == '2':
	n = int(input('Enter the value of Σfi / n = '))
	n2 = n/2
	print('See if any of the C.I. has this value = ',n/2,'\n[IF found then that ci will be your median class')
	f = int(input('Enter the value of frequency of median class = '))
	cf = int(input('Enter the Sum of Frequencies above the median class[eg.- 24] = '))
	l = int(input('Enter the Lower Limit of the median class = '))
	h = int(input('Enter the CLass Size [upper limit - lower limit]= '))
	upper = (n2 - cf) * h
	middle = upper / f
	lower = l + middle
	print('Your Median is = ',lower)
elif choice == '3':
	print('Please see the max frequency class [that class will be your modal class] ')
	l = int(input('Enter the lower limit of modal class = '))
	h = int(input('Enter the Class Size [upper limit - lower limit = class size] = '))
	f1 = int(input('Enter the frequency of modal class = '))
	f0 = int(input('Enter the frequency of the class above the modal class = '))
	f2 = int(input('Enter the frequency of the class below the modal class = '))
	dup =(f1 - f0)/(2*f1 - f0 - f2)
	dmid = dup * h
	dow = l + dmid
	print('Your MODE is = ',dow)